# Generated by Django 3.1.7 on 2021-07-27 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0114_auto_20210727_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeRequestCash_PH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever_name', models.CharField(max_length=20, null=True)),
                ('reciever_name2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reciever Name (2)')),
                ('reciever_name3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reciever Name (3)')),
                ('reciever_name4', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reciever Name (4)')),
                ('reciever_name5', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reciever Name (5)')),
                ('Address_of_reciever', models.CharField(max_length=100, null=True, verbose_name='Reciever Address')),
                ('Address_of_reciever2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reciever Address (2)')),
                ('Address_of_reciever3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reciever Address (3)')),
                ('Address_of_reciever4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reciever Address (4)')),
                ('Address_of_reciever5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reciever Address (5)')),
                ('Package_description', models.CharField(max_length=100, null=True)),
                ('Package_description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Package Description (2)')),
                ('Package_description3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Package Description (3)')),
                ('Package_description4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Package Description (4)')),
                ('Package_description5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Package Description (5)')),
                ('Choice_for_TP', models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)'), ('Van', 'Van')], default='Bike', max_length=100, null=True)),
                ('Your_location', models.CharField(help_text='The location we would pick the item from', max_length=100, null=True, verbose_name='Pickup Location')),
                ('reciever_phone_number', models.CharField(help_text='This Format:070xxxxxxxx', max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Number')),
                ('reciever_phone_number2', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Number(2)')),
                ('reciever_phone_number3', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Number(3)')),
                ('reciever_phone_number4', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Number(4)')),
                ('reciever_phone_number5', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Number(5)')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True)),
                ('Loading_choice', models.CharField(max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('Amount_Paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Amount_Payable', models.IntegerField(null=True)),
                ('order_id', models.CharField(default=0, max_length=10, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
