# Generated by Django 3.1.7 on 2021-07-27 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0115_auto_20210727_1211'),
        ('PortHarcourt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerequestcash_ph',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PH_adminNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('item_created', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('order_id', models.CharField(default=0, max_length=10, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
        ),
    ]
