# Generated by Django 3.1.7 on 2021-07-28 21:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0116_auto_20210728_2238'),
        ('PortHarcourt', '0002_auto_20210727_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerequestcash_ph',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Errand_service_PH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bread', 'Bread'), ('Pizza', 'Pizza'), ('Fruits', 'Fruits'), ('Food', 'Food'), ('Gas', 'Gas'), ('Others', 'Others'), ('Drugs', 'Drugs'), ('Fuel', 'Fuel'), ('Ice Cream', 'Ice Cream'), ('Shawarma', 'Shawarma')], max_length=100, null=True)),
                ('fuel_per_amount', models.IntegerField(help_text='Enter amount for fuel needed (Not litres)', null=True, verbose_name='Petrol Amount')),
                ('payment_channel', models.CharField(choices=[('Card/Transfer', 'Card/Transfer')], max_length=100, null=True, verbose_name='Payment Choice')),
                ('Bread_brand_name', models.CharField(max_length=100, null=True, verbose_name='Bread Name')),
                ('Quantity', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='Further description', max_length=100, null=True)),
                ('Enter_amount', models.IntegerField(help_text='Cost to purchase items', null=True, verbose_name='Amount')),
                ('Drug_store', models.CharField(help_text="Write 'None' if None", max_length=100, null=True, verbose_name='Pharmacy Name')),
                ('Drug_store_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pharmacy Location')),
                ('Drug_name', models.CharField(help_text='Must be an over the counter drug', max_length=200, null=True)),
                ('Gas_Quantity', models.IntegerField(help_text='Enter the quantity of gas you want refilled (1-12kg)', null=True)),
                ('Shawarma_store', models.CharField(help_text='write None if None', max_length=100, null=True)),
                ('Shawarma_desc', models.CharField(choices=[('Special', 'Special'), ('Chicken', 'Chicken'), ('Beef', 'Beef')], max_length=100, null=True, verbose_name='Preference')),
                ('pizza_store', models.CharField(max_length=100, null=True, verbose_name='Place of Purchase')),
                ('Pizza_desc', models.CharField(max_length=100, null=True, verbose_name='Type of Pizza')),
                ('ice_Cream_desc', models.CharField(max_length=100, null=True, verbose_name='Ice Cream Description')),
                ('ice_Cream_store', models.CharField(max_length=100, null=True)),
                ('fruits_description', models.CharField(max_length=100, null=True)),
                ('fruits_purchase_store', models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Location')),
                ('medical_prescription', models.FileField(blank=True, default='default.jpg', help_text='Alternatively upload precription', null=True, upload_to='medical_presciption')),
                ('Food_Vendor', models.CharField(max_length=100, null=True)),
                ('Food_description', models.CharField(max_length=200, null=True)),
                ('your_location', models.CharField(max_length=100, null=True)),
                ('order_id', models.CharField(max_length=7, null=True)),
                ('Ps_reference', models.CharField(max_length=10, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('profit', models.IntegerField(default=0, null=True)),
                ('Amount_Paid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Amount_Payable', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('On Route for Delivery', 'On route for Delivery'), ('Pending', 'Pending'), ('Purchase in Process', 'Purchase in Process'), ('Delivered', 'Delivered')], default='Pending', max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
