# Generated by Django 3.1.7 on 2021-08-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortHarcourt', '0004_auto_20210803_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand_service_ph',
            name='category',
            field=models.CharField(choices=[('Shawarma', 'Shawarma'), ('Pizza', 'Pizza'), ('Food', 'Food'), ('Others', 'Others'), ('Fruits', 'Fruits'), ('Ice Cream', 'Ice Cream'), ('Fuel', 'Fuel'), ('Drugs', 'Drugs'), ('Bread', 'Bread'), ('Gas', 'Gas')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service_ph',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Purchase in Process', 'Purchase in Process'), ('Delivered', 'Delivered'), ('On Route for Delivery', 'On route for Delivery')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash_ph',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
    ]
