# Generated by Django 3.1.7 on 2021-08-10 10:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0126_auto_20210810_1134'),
        ('PortHarcourt', '0012_auto_20210810_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleets_PH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_plate_number', models.CharField(max_length=100, null=True)),
                ('Tracker_id', models.CharField(max_length=100, null=True)),
                ('Tracker_phone_num', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle')], max_length=100, null=True)),
                ('vechile_name', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RidersProfile_PH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,12}$')])),
                ('Address', models.CharField(max_length=100, null=True)),
                ('verified_gurantor', models.BooleanField(default=False)),
                ('gurantor_name', models.CharField(max_length=100, null=True)),
                ('gurantor_address', models.CharField(max_length=100, null=True)),
                ('Riders_profile', models.CharField(max_length=100, null=True)),
                ('busy', models.BooleanField(default=False)),
                ('attached_bike', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PortHarcourt.fleets_ph')),
            ],
        ),
        migrations.AddField(
            model_name='makerequestcash_ph',
            name='Cancelation_Reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service_ph',
            name='category',
            field=models.CharField(choices=[('Ice Cream', 'Ice Cream'), ('Gas', 'Gas'), ('Bread', 'Bread'), ('Drugs', 'Drugs'), ('Food', 'Food'), ('Fruits', 'Fruits'), ('Shawarma', 'Shawarma'), ('Fuel', 'Fuel'), ('Others', 'Others'), ('Pizza', 'Pizza')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service_ph',
            name='status',
            field=models.CharField(choices=[('Purchase in Process', 'Purchase in Process'), ('On Route for Delivery', 'On route for Delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk_ph',
            name='customer_payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer & Cash', 'Transfer & Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk_ph',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash_ph',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Shopping_PH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List_Items', models.TextField(max_length=500, null=True)),
                ('Place_of_purchase', models.CharField(help_text='Specify a place for purchase if any.', max_length=100, null=True)),
                ('Note', models.CharField(blank=True, help_text='Any further description', max_length=200, null=True)),
                ('Address', models.CharField(max_length=200, null=True, verbose_name='Delivery Address')),
                ('Amount', models.IntegerField(help_text='Enter an estimated amount, our charges Inclusive.', null=True)),
                ('Accept_Terms', models.BooleanField(default=False, help_text='Accept our Terms and Condition as regards this method')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('At the Mall', 'At the Mall'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Charge', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Item_Cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Amount_Refunded', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('order_id', models.CharField(max_length=10, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('payment_channel', models.CharField(choices=[('Card/Transfer', 'Card/Transfer')], max_length=100, null=True, verbose_name='Payment Choice')),
                ('Cancelation_Reason', models.CharField(blank=True, max_length=100, null=True)),
                ('Ps_reference', models.CharField(max_length=10, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
                ('riders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PortHarcourt.ridersprofile_ph')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AlterField(
            model_name='errand_service_ph',
            name='riders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PortHarcourt.ridersprofile_ph'),
        ),
        migrations.AlterField(
            model_name='front_desk_ph',
            name='riders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PortHarcourt.ridersprofile_ph'),
        ),
        migrations.AlterField(
            model_name='makerequestcash_ph',
            name='riders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PortHarcourt.ridersprofile_ph'),
        ),
    ]
