# Generated by Django 3.1.7 on 2021-09-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortHarcourt', '0019_auto_20210823_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand_service_ph',
            name='category',
            field=models.CharField(choices=[('Shawarma', 'Shawarma'), ('Gas', 'Gas'), ('Others', 'Others'), ('Pizza', 'Pizza'), ('Food', 'Food'), ('Fuel', 'Fuel'), ('Bread', 'Bread'), ('Ice Cream', 'Ice Cream'), ('Fruits', 'Fruits'), ('Drugs', 'Drugs')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service_ph',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On Route for Delivery', 'On route for Delivery'), ('Pending', 'Pending'), ('Purchase in Process', 'Purchase in Process')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk_ph',
            name='customer_payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Transfer', 'Transfer'), ('Cash', 'Cash'), ('Transfer & Cash', 'Transfer & Cash')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopping_ph',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
