# Generated by Django 3.1.7 on 2021-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortHarcourt', '0021_auto_20210915_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand_service_ph',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Special', 'Special'), ('Chicken', 'Chicken'), ('Beef', 'Beef')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service_ph',
            name='category',
            field=models.CharField(choices=[('Ice Cream', 'Ice Cream'), ('Gas', 'Gas'), ('Food', 'Food'), ('Drugs', 'Drugs'), ('Pizza', 'Pizza'), ('Others', 'Others'), ('Shawarma', 'Shawarma'), ('Bread', 'Bread'), ('Fuel', 'Fuel'), ('Fruits', 'Fruits')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service_ph',
            name='status',
            field=models.CharField(choices=[('On Route for Delivery', 'On route for Delivery'), ('Purchase in Process', 'Purchase in Process'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk_ph',
            name='customer_payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer & Cash', 'Transfer & Cash'), ('Transfer', 'Transfer'), ('Card', 'Card')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk_ph',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash_ph',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping_ph',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall')], default='Pending', max_length=20, null=True),
        ),
    ]
