# Generated by Django 3.1.7 on 2021-09-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortHarcourt', '0022_auto_20210921_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand_service_ph',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Beef', 'Beef'), ('Special', 'Special'), ('Chicken', 'Chicken')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service_ph',
            name='category',
            field=models.CharField(choices=[('Bread', 'Bread'), ('Shawarma', 'Shawarma'), ('Drugs', 'Drugs'), ('Ice Cream', 'Ice Cream'), ('Others', 'Others'), ('Fuel', 'Fuel'), ('Fruits', 'Fruits'), ('Gas', 'Gas'), ('Pizza', 'Pizza'), ('Food', 'Food')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service_ph',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Purchase in Process', 'Purchase in Process'), ('Delivered', 'Delivered'), ('On Route for Delivery', 'On route for Delivery')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk_ph',
            name='customer_payment_method',
            field=models.CharField(choices=[('Transfer & Cash', 'Transfer & Cash'), ('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk_ph',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash_ph',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping_ph',
            name='status',
            field=models.CharField(choices=[('At the Mall', 'At the Mall'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
