# Generated by Django 3.1.7 on 2021-11-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortHarcourt', '0032_auto_20211101_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand_service_ph',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Beef', 'Beef'), ('Special', 'Special'), ('Chicken', 'Chicken')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service_ph',
            name='category',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Ice Cream', 'Ice Cream'), ('Drugs', 'Drugs'), ('Fruits', 'Fruits'), ('Shawarma', 'Shawarma'), ('Fuel', 'Fuel'), ('Bread', 'Bread'), ('Food', 'Food'), ('Pizza', 'Pizza'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service_ph',
            name='status',
            field=models.CharField(choices=[('Purchase in Process', 'Purchase in Process'), ('On Route for Delivery', 'On route for Delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk_ph',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash_ph',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping_ph',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('At the Mall', 'At the Mall')], default='Pending', max_length=20, null=True),
        ),
    ]
