---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fllsdnqe/Testing/
    - /bin/cp -r Affiliate $DEPLOYPATH
    - /bin/cp -r BikeControl $DEPLOYPATH
    - /bin/cp -r FDS_app $DEPLOYPATH
    - /bin/cp -r FDS_site $DEPLOYPATH
    - /bin/cp -r Management $DEPLOYPATH
    - /bin/cp -r PortHarcourt $DEPLOYPATH
    - /bin/cp -r users $DEPLOYPATH
    - /bin/cp manage.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH