# Generated by Django 3.1.7 on 2021-05-29 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0064_auto_20210529_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_plate_number', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle')], max_length=100, null=True)),
                ('vechile_name', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RidersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,12}$')])),
                ('Address', models.CharField(max_length=100, null=True)),
                ('verified_gurantor', models.BooleanField(default=False)),
                ('gurantor_name', models.CharField(max_length=100, null=True)),
                ('gurantor_address', models.CharField(max_length=100, null=True)),
                ('attached_bike', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BikeControl.fleets')),
            ],
        ),
        migrations.CreateModel(
            name='RidersDeliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staus', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Transfered', 'Transfered'), ('Canceled', 'Canceled')], default='Pending', max_length=100, null=True)),
                ('dispute', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('anonymous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.anonymous')),
                ('cash_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.makerequestcash')),
                ('e_payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.makerequest')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BikeControl.ridersprofile')),
                ('shopping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shopping')),
                ('veichle_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BikeControl.fleets')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
