# Generated by Django 3.1.7 on 2021-07-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeControl', '0002_auto_20210629_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleets',
            name='Tracker_id',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fleets',
            name='Tracker_phone_num',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
