# Generated by Django 3.1.7 on 2021-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeControl', '0004_auto_20210715_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridersprofile',
            name='busy',
            field=models.BooleanField(default=True),
        ),
    ]
