# Generated by Django 3.1.7 on 2021-07-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeControl', '0005_auto_20210715_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleets',
            name='Tracker_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fleets',
            name='Tracker_phone_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
