# Generated by Django 3.1.7 on 2021-07-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeControl', '0006_auto_20210723_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleets',
            name='Tracker_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fleets',
            name='Tracker_phone_num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
