import Vue from 'vue'
import VueRouter from 'vue-router'

import allFleet from '@/components/allFleet'
import AllRiders from '@/components/AllRiders'
import AllCashRequest from '@/components/AllCashRequest'
import AllErrandService from '@/components/AllErrandService'
import AllFrontDesk from '@/components/AllFrontDesk'
import AllShopping from '@/components/AllShopping'
import AllAdmin from '@/components/AllAdmin'