# Generated by Django 3.1.7 on 2021-10-08 14:06

import Affiliate.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BikeControl', '0007_auto_20210726_1203'),
        ('users', '0141_auto_20211008_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referal_ID', models.CharField(editable=False, max_length=5, null=True, unique=True)),
                ('Date_Joined', models.DateTimeField(blank=True, default=None, null=True)),
                ('Total_Referal', models.IntegerField(default=0, null=True)),
                ('Amount_Genreated', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Amount_Credited', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Wallet_Balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Profit_Generated', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Marketer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Account_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Number', models.IntegerField(editable=False, unique=True, validators=[Affiliate.models.Bank_Account_Details.Check_Len])),
                ('Account_Name', models.CharField(editable=False, max_length=100, null=True, unique=True)),
                ('Bank_Name', models.CharField(max_length=100, null=True)),
                ('marketer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Affiliate.affiliate_group')),
            ],
        ),
        migrations.CreateModel(
            name='Request_Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Debit_amount', models.IntegerField(default=0, null=True)),
                ('Date_Requested', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=10, null=True)),
                ('Transaction_ID', models.CharField(editable=False, max_length=10, null=True)),
                ('Amount_credited', models.IntegerField(null=True)),
                ('Payment_date', models.DateField(default=None, null=True)),
                ('Account_credited_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Affiliate.bank_account_details')),
                ('Select_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='Affiliate.bank_account_details')),
                ('marketer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Affiliate.affiliate_group')),
            ],
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Referal_ID', models.CharField(editable=False, max_length=5, null=True)),
                ('Choice_for_TP', models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)')], max_length=10, null=True)),
                ('Delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery')], editable=False, max_length=20, null=True)),
                ('Trips_count', models.IntegerField(default=0, null=True)),
                ('Delivery_Fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Customer_percentage_profit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FLLS_perentage_profit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Order_ID', models.CharField(max_length=8, null=True)),
                ('Rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BikeControl.ridersprofile')),
                ('marketer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Affiliate.affiliate_group')),
            ],
        ),
    ]
