# Generated by Django 3.1.7 on 2021-10-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affiliate', '0004_auto_20211012_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrals',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='Delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request_payout',
            name='Payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Canceled', 'Canceled')], default='Pending', max_length=10, null=True),
        ),
    ]
