# Generated by Django 3.1.7 on 2021-10-12 15:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affiliate', '0006_auto_20211012_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate_group',
            name='Amount_Credited',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate_group',
            name='Amount_Genreated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate_group',
            name='Profit_Generated',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate_group',
            name='Wallet_Balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='Delivery_status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], editable=False, max_length=20, null=True),
        ),
    ]
