# Generated by Django 3.1.7 on 2021-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affiliate', '0007_auto_20211012_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='Delivery_status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request_payout',
            name='Payment_status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10, null=True),
        ),
    ]
