# Generated by Django 3.1.7 on 2021-10-15 13:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affiliate', '0009_auto_20211014_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate_group',
            name='Amount_Credited',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate_group',
            name='Amount_Genreated',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate_group',
            name='Profit_Generated',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate_group',
            name='Wallet_Balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='Delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request_payout',
            name='Payment_status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10, null=True),
        ),
    ]
