# Generated by Django 3.1.7 on 2021-10-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affiliate', '0014_auto_20211020_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_admin',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
