# Generated by Django 3.1.7 on 2021-10-21 13:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affiliate', '0015_auto_20211021_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate_group',
            name='Tempoary_wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='Delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request_payout',
            name='Payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Canceled', 'Canceled')], default='Pending', max_length=10, null=True),
        ),
    ]
