# Generated by Django 3.1.7 on 2021-11-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affiliate', '0019_auto_20211101_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='Delivery_status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], editable=False, max_length=20, null=True),
        ),
    ]
