# Generated by Django 3.1.7 on 2021-11-10 09:48

import Affiliate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affiliate', '0021_auto_20211101_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account_details',
            name='Account_Number',
            field=models.BigIntegerField(unique=True, validators=[Affiliate.models.Bank_Account_Details.Check_Len]),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='Delivery_status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request_payout',
            name='Payment_status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10, null=True),
        ),
    ]
