# Generated by Django 3.1.7 on 2021-11-13 16:17

import Affiliate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affiliate', '0022_auto_20211110_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account_details',
            name='Account_Number',
            field=models.CharField(max_length=10, unique=True, validators=[Affiliate.models.Bank_Account_Details.Check_Len]),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='Delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request_payout',
            name='Payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=10, null=True),
        ),
    ]
