# Generated by Django 3.1.7 on 2021-03-31 13:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('phone_number', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('state', models.CharField(choices=[('Port', 'Port Harcourt'), ('Cross', 'Cross River')], max_length=15, null=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('email', models.EmailField(max_length=100, null=True)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MakeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever_name', models.CharField(max_length=20, null=True)),
                ('Address_of_reciever', models.CharField(max_length=50, null=True)),
                ('Package_description', models.CharField(blank=True, max_length=25)),
                ('Choice_for_TP', models.CharField(choices=[('Bi', 'Bike'), ('Ke', 'Trycycle (Keke)')], max_length=20, null=True)),
                ('Your_location', models.CharField(max_length=30, null=True)),
                ('reciever_phone_number', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='pending', max_length=20, null=True)),
                ('Amount', models.CharField(default=0, max_length=20, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ForPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('For_online_payment', models.BooleanField(default=False)),
                ('paystack_access_code', models.CharField(default='', max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('money_paid', models.CharField(default='500', max_length=10, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
