# Generated by Django 3.1.7 on 2021-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='pending', max_length=20, null=True),
        ),
    ]
