# Generated by Django 3.1.7 on 2021-03-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210331_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forpayments',
            name='For_online_payment',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='pending', max_length=20, null=True),
        ),
    ]
