# Generated by Django 3.1.7 on 2021-04-02 08:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210331_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerequest',
            name='cash_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='pending', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MakeRequest_cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever_name', models.CharField(max_length=20, null=True)),
                ('Address_of_reciever', models.CharField(max_length=50, null=True)),
                ('Package_description', models.CharField(blank=True, max_length=25)),
                ('Choice_for_TP', models.CharField(choices=[('Bi', 'Bike'), ('Ke', 'Trycycle (Keke)')], default='Bike', max_length=20, null=True)),
                ('Your_location', models.CharField(max_length=30, null=True)),
                ('reciever_phone_number', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='pending', max_length=20, null=True)),
                ('cash_payment', models.BooleanField(default=True)),
                ('Amount', models.CharField(default=0, max_length=20, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
        ),
    ]
