# Generated by Django 3.1.7 on 2021-04-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210403_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List_Items', models.TextField(help_text='Fill in your list of items you want us to purchase and pick for you', max_length=500, null=True)),
                ('Place_of_purchase', models.CharField(help_text='Specify a place of for purchase if any.', max_length=100, null=True)),
                ('Note', models.CharField(help_text='Any further description', max_length=200, null=True)),
                ('Address', models.CharField(help_text='Specify the address we would deliver Your items to', max_length=200, null=True)),
                ('Amount', models.CharField(help_text='Enter an estimated amount, our charges Inclusive', max_length=7, null=True)),
                ('Accept_Terms', models.BooleanField(default=False, help_text='Accept our Terms and Condition as regards this method')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='pending', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='verifyPayment',
        ),
    ]
