# Generated by Django 3.1.7 on 2021-04-04 10:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210404_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forpayments',
            name='For_online_payment',
        ),
        migrations.RemoveField(
            model_name='forpayments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='makerequest',
            name='cash_payment',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='date',
        ),
        migrations.AddField(
            model_name='forpayments',
            name='For_shopping_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shopping'),
        ),
        migrations.AddField(
            model_name='forpayments',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='charge_id',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopping',
            name='charge_id',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='shopping',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='forpayments',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='forpayments',
            name='paystack_access_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='pending', max_length=20, null=True),
        ),
    ]
