# Generated by Django 3.1.7 on 2021-04-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210404_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='charge_id',
        ),
        migrations.AddField(
            model_name='shopping',
            name='Amount_Refunded',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='Charge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='Item_Cost',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='Total',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='amount_paid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('At the Mall', 'At the Mall'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
    ]
