# Generated by Django 3.1.7 on 2021-04-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210407_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makerequestcash',
            old_name='Amount',
            new_name='Amount_Paid',
        ),
        migrations.RenameField(
            model_name='makerequestcash',
            old_name='cash_payment',
            new_name='paid',
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
    ]
