# Generated by Django 3.1.7 on 2021-04-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210412_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('At the Mall', 'At the Mall'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
