# Generated by Django 3.1.7 on 2021-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210414_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerequest',
            name='Choice_for_TP',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='Choice_for_TP',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)')], default='Bike', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
    ]
