# Generated by Django 3.1.7 on 2021-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210417_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivered',
            name='For_cash_payment',
        ),
        migrations.RemoveField(
            model_name='delivered',
            name='For_online_payment',
        ),
        migrations.RemoveField(
            model_name='delivered',
            name='For_shopping_payment',
        ),
        migrations.AddField(
            model_name='delivered',
            name='Item_delivered',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('At the Mall', 'At the Mall'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
    ]
