# Generated by Django 3.1.7 on 2021-05-15 21:14

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210423_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makerequest',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='makerequestcash',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='shopping',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='delivered',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='forpayments',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('At the Mall', 'At the Mall'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
