# Generated by Django 3.1.7 on 2021-05-18 08:29

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20210516_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='delivered',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='forpayments',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='order_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', default=0, min_length=7, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('At the Mall', 'At the Mall')], default='Pending', max_length=20, null=True),
        ),
    ]
