# Generated by Django 3.1.7 on 2021-05-19 20:26

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20210519_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_description', models.CharField(blank=True, help_text='The current location of the reciever.', max_length=100, null=True)),
                ('Choice_for_TP', models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)')], default='Bike', max_length=20, null=True)),
                ('Your_location', models.CharField(help_text='The location we would pick your item from', max_length=30, null=True, verbose_name='Pickup Location')),
                ('Your_phone_number', models.CharField(help_text='Contact of the person recieving, or picking the item from', max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Your Phone Number')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('Amount_Paid', models.CharField(default=0, max_length=20, null=True)),
                ('order_id', models.CharField(default=0, max_length=10, null=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.RemoveField(
            model_name='makerequestcash',
            name='id_search',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='id_search',
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='Your_location',
            field=models.CharField(help_text='The location we would pick the item from', max_length=30, null=True, verbose_name='Pickup Location'),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='reciever_phone_number',
            field=models.CharField(help_text='Enter phone number of the person to recieve this or pick item from', max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Phone Number'),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
    ]
