# Generated by Django 3.1.7 on 2021-05-21 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20210519_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='Amount_Paid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='Choice_for_TP',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)')], default='Bike', help_text='Depending on the item size, choose what best suit your item best handling. COST: Bike N500, Tricycle N1000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='Your_phone_number',
            field=models.CharField(help_text='Enter an active phone number', max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Your Phone Number'),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall')], default='Pending', max_length=20, null=True),
        ),
    ]
