# Generated by Django 3.1.7 on 2021-06-08 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20210603_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Alt_phone_num',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number (2nd)'),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='Choice_for_TP',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)'), ('Van', 'Van')], default='Bike', help_text=' COST: Bike N500, Tricycle N1000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='Package_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='Your_phone_number',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Your Phone Number'),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='Choice_for_TP',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)'), ('Van', 'Van')], default='Bike', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='Choice_for_TP',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)'), ('Van', 'Van')], default='Bike', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('At the Mall', 'At the Mall'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
    ]
