# Generated by Django 3.1.7 on 2021-06-08 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20210608_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerequestcash',
            name='Address_of_reciever2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Address_of_reciever3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Address_of_reciever4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Address_of_reciever5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Package_description2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Package_description3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Package_description4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Package_description5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='reciever_name2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='reciever_name3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='reciever_name4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='reciever_name5',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='reciever_phone_number2',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Phone Number1'),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='reciever_phone_number3',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Phone Number2'),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='reciever_phone_number4',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Phone Number3'),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='reciever_phone_number5',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Phone Number4'),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='Choice_for_TP',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)'), ('Van', 'Van')], default='Bike', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('At the Mall', 'At the Mall'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
