# Generated by Django 3.1.7 on 2021-06-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_auto_20210613_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerequest',
            name='Area',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], default='Choose Reciever Area', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='Area_2',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], default='Choose Reciever Area', max_length=100, null=True, verbose_name='Area(2)'),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='Area_3',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], default='Choose Reciever Area', max_length=100, null=True, verbose_name='Area(3)'),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='Area_4',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], default='Choose Reciever Area', max_length=100, null=True, verbose_name='Area(4)'),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='Area_5',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], default='Choose Reciever Area', max_length=100, null=True, verbose_name='Area(5)'),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='Your_area',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Area',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], default='Choose Reciever Area', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Area_2',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], default='Choose Reciever Area', max_length=100, null=True, verbose_name='Area(2)'),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Area_3',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], default='Choose Reciever Area', max_length=100, null=True, verbose_name='Area(3)'),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Area_4',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], default='Choose Reciever Area', max_length=100, null=True, verbose_name='Area(4)'),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Area_5',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], default='Choose Reciever Area', max_length=100, null=True, verbose_name='Area(5)'),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='Your_area',
            field=models.CharField(choices=[('CALABAR-SOUTH', 'CALABAR-SOUTH'), ('CALABAR-MUNICIPAL', 'CALABAR-MUNICIPAL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
    ]
