# Generated by Django 3.1.7 on 2021-06-17 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_auto_20210616_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall')], default='Pending', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Errand_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Ice Cream', 'Ice Cream'), ('Drugs', 'Drugs'), ('Bread', 'Bread'), ('Pizza', 'Pizza'), ('Shawarma', 'Shawarma'), ('Gas', 'Gas'), ('Fruits', 'Fruits'), ('Fuel', 'Fuel')], max_length=100, null=True)),
                ('fuel_per_amount', models.IntegerField(help_text='25Ltrs max per order (N163/ltr, N4075-25ltrs', null=True, verbose_name='Petrol Amount')),
                ('payment_channel', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=100, null=True, verbose_name='Payment Choice')),
                ('Bread_brand_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bread Name')),
                ('Quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('Enter_amount', models.IntegerField(help_text='Cost to purchase items', null=True, verbose_name='Amount')),
                ('Drug_store', models.CharField(blank=True, max_length=100, null=True)),
                ('Drug_name', models.CharField(help_text='Must be an over the counter drug', max_length=200, null=True)),
                ('Gas_Quantity', models.CharField(help_text='Kg Amount of Gas you want reffilled', max_length=20, null=True)),
                ('Shawarma_store', models.CharField(blank=True, max_length=100, null=True)),
                ('Shawarma_desc', models.CharField(choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Special', 'Special')], max_length=100, null=True, verbose_name='Preference')),
                ('pizza_store', models.CharField(max_length=100, null=True, verbose_name='Place of Purchase')),
                ('Pizza_desc', models.CharField(max_length=100, null=True, verbose_name='Type of Pizza')),
                ('ice_Cream_desc', models.CharField(max_length=100, null=True, verbose_name='Ice Cream Description')),
                ('ice_Cream_store', models.CharField(max_length=100, null=True)),
                ('fruits_description', models.CharField(max_length=100, null=True)),
                ('fruits_purchase_store', models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Location')),
                ('your_location', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(max_length=7, null=True)),
                ('Ps_reference', models.CharField(max_length=10, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('Amount_Paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Amount_Payable', models.IntegerField(default=0, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
        ),
    ]
