# Generated by Django 3.1.7 on 2021-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_auto_20210617_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand_service',
            name='medical_prescription',
            field=models.FileField(blank=True, help_text='Alternatively upload precription', null=True, upload_to='medical_presciption'),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Drug_store',
            field=models.CharField(blank=True, help_text="Write 'None' if none", max_length=100, null=True, verbose_name='Pharmacy Name'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Gas_Quantity',
            field=models.IntegerField(help_text='Enter the quantity of gas you want refilled (1-12kg)', null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Drugs', 'Drugs'), ('Fruits', 'Fruits'), ('Ice Cream', 'Ice Cream'), ('Others', 'Others'), ('Pizza', 'Pizza'), ('Gas', 'Gas'), ('Shawarma', 'Shawarma'), ('Fuel', 'Fuel'), ('Bread', 'Bread')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='type',
            field=models.CharField(choices=[('Multiple', 'Multiple'), ('Single', 'Single')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='type',
            field=models.CharField(choices=[('Multiple', 'Multiple'), ('Single', 'Single')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('At the Mall', 'At the Mall'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
    ]
