# Generated by Django 3.1.7 on 2021-06-20 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_auto_20210619_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Special', 'Special'), ('Chicken', 'Chicken'), ('Beef', 'Beef')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Others', 'Others'), ('Gas', 'Gas'), ('Shawarma', 'Shawarma'), ('Fuel', 'Fuel'), ('Pizza', 'Pizza'), ('Fruits', 'Fruits'), ('Ice Cream', 'Ice Cream'), ('Bread', 'Bread'), ('Drugs', 'Drugs'), ('Food', 'Food')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='description',
            field=models.CharField(blank=True, help_text='Further description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='medical_prescription',
            field=models.FileField(blank=True, default='default.jpg', help_text='Alternatively upload precription', null=True, upload_to='medical_presciption'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('On Route for Delivery', 'On route for Delivery'), ('Purchase in Process', 'Purchase in Process'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('At the Mall', 'At the Mall'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Front_desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_location', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_destination', models.CharField(blank=True, max_length=200, null=True)),
                ('Choice_for_TP', models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)'), ('Van', 'Van')], max_length=20, null=True)),
                ('Delivery_type', models.CharField(choices=[('single', 'single'), ('multiple', 'multiple')], max_length=20, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Enter_amount', models.IntegerField(help_text='Cost to purchase items', null=True, verbose_name='Amount')),
                ('Note', models.CharField(choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)'), ('Van', 'Van')], max_length=20, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('payments_confirmed', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('Amount_Paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Amount_Payable', models.IntegerField(default=0, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
        ),
    ]
