# Generated by Django 3.1.7 on 2021-06-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_auto_20210620_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_desk',
            name='order_id',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Special', 'Special')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Shawarma', 'Shawarma'), ('Ice Cream', 'Ice Cream'), ('Gas', 'Gas'), ('Drugs', 'Drugs'), ('Fruits', 'Fruits'), ('Others', 'Others'), ('Pizza', 'Pizza'), ('Fuel', 'Fuel'), ('Bread', 'Bread')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('On Route for Delivery', 'On route for Delivery'), ('Pending', 'Pending'), ('Purchase in Process', 'Purchase in Process'), ('Delivered', 'Delivered')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='Delivery_type',
            field=models.CharField(choices=[('Pick & Drop', 'Pick & Drop'), ('Errand', 'Errand')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='Note',
            field=models.CharField(blank='True', choices=[('Bike', 'Bike'), ('Tricycle', 'Tricycle (Keke)'), ('Van', 'Van')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('At the Mall', 'At the Mall'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
    ]
