# Generated by Django 3.1.7 on 2021-06-29 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_auto_20210622_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errand_service',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='front_desk',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Alt_phone_num',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number (2nd)'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Bread_brand_name',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='Bread Name'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Drug_name',
            field=models.CharField(default=0, help_text='Must be an over the counter drug', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Drug_store',
            field=models.CharField(default=0, help_text="Write 'None' if none", max_length=100, null=True, verbose_name='Pharmacy Name'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Enter_amount',
            field=models.IntegerField(default=0, help_text='Cost to purchase items', null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Food_Vendor',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Food_description',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Pizza_desc',
            field=models.CharField(default=0, max_length=100, null=True, verbose_name='Type of Pizza'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Ps_reference',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Quantity',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Beef', 'Beef'), ('Special', 'Special'), ('Chicken', 'Chicken')], default=0, max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_store',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Shawarma', 'Shawarma'), ('Bread', 'Bread'), ('Drugs', 'Drugs'), ('Ice Cream', 'Ice Cream'), ('Food', 'Food'), ('Others', 'Others'), ('Gas', 'Gas'), ('Fruits', 'Fruits'), ('Fuel', 'Fuel'), ('Pizza', 'Pizza')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='description',
            field=models.CharField(blank=True, default=0, help_text='Further description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='fruits_description',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='fruits_purchase_store',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='Purchase Location'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='fuel_per_amount',
            field=models.IntegerField(default=0, help_text='25Ltrs max per order (N163/ltr, N4075-25ltrs', null=True, verbose_name='Petrol Amount'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='ice_Cream_desc',
            field=models.CharField(default=0, max_length=100, null=True, verbose_name='Ice Cream Description'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='ice_Cream_store',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='order_id',
            field=models.CharField(default=0, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='payment_channel',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default=0, max_length=100, null=True, verbose_name='Payment Choice'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='pizza_store',
            field=models.CharField(default=0, max_length=100, null=True, verbose_name='Place of Purchase'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('On Route for Delivery', 'On route for Delivery'), ('Delivered', 'Delivered'), ('Purchase in Process', 'Purchase in Process'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('At the Mall', 'At the Mall'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
