# Generated by Django 3.1.7 on 2021-07-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_auto_20210702_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='TermsAgreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Special', 'Special')], default=0, max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Bread', 'Bread'), ('Ice Cream', 'Ice Cream'), ('Fuel', 'Fuel'), ('Gas', 'Gas'), ('Shawarma', 'Shawarma'), ('Others', 'Others'), ('Pizza', 'Pizza'), ('Fruits', 'Fruits'), ('Food', 'Food'), ('Drugs', 'Drugs')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Purchase in Process', 'Purchase in Process'), ('Delivered', 'Delivered'), ('On Route for Delivery', 'On route for Delivery')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('At the Mall', 'At the Mall')], default='Pending', max_length=20, null=True),
        ),
    ]
