# Generated by Django 3.1.7 on 2021-07-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_auto_20210703_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TermsAgreement',
            field=models.BooleanField(default=False, verbose_name='Terms & Agreement'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Beef', 'Beef'), ('Chicken', 'Chicken'), ('Special', 'Special')], default=0, max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Shawarma', 'Shawarma'), ('Gas', 'Gas'), ('Others', 'Others'), ('Food', 'Food'), ('Fuel', 'Fuel'), ('Drugs', 'Drugs'), ('Bread', 'Bread'), ('Fruits', 'Fruits'), ('Pizza', 'Pizza'), ('Ice Cream', 'Ice Cream')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Purchase in Process', 'Purchase in Process'), ('On Route for Delivery', 'On route for Delivery')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='type',
            field=models.CharField(choices=[('Multiple', 'Multiple'), ('Single', 'Single')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='type',
            field=models.CharField(choices=[('Multiple', 'Multiple'), ('Single', 'Single')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall')], default='Pending', max_length=20, null=True),
        ),
    ]
