# Generated by Django 3.1.7 on 2021-07-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_auto_20210703_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand_service',
            name='Drug_store_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pharmacy Location'),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Special', 'Special'), ('Chicken', 'Chicken'), ('Beef', 'Beef')], default=0, max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Bread', 'Bread'), ('Shawarma', 'Shawarma'), ('Fruits', 'Fruits'), ('Food', 'Food'), ('Others', 'Others'), ('Drugs', 'Drugs'), ('Ice Cream', 'Ice Cream'), ('Gas', 'Gas'), ('Fuel', 'Fuel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Route for Delivery', 'On route for Delivery'), ('Purchase in Process', 'Purchase in Process'), ('Delivered', 'Delivered')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('At the Mall', 'At the Mall')], default='Pending', max_length=20, null=True),
        ),
    ]
