# Generated by Django 3.1.7 on 2021-07-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_auto_20210704_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='payment_channel',
            field=models.CharField(choices=[('Card/Transfer', 'Card/Transfer')], max_length=100, null=True, verbose_name='Payment Choice'),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Amount_Paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Amount_Payable',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Bread_brand_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bread Name'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Drug_name',
            field=models.CharField(help_text='Must be an over the counter drug', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Drug_store',
            field=models.CharField(help_text="Write 'None' if none", max_length=100, null=True, verbose_name='Pharmacy Name'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Enter_amount',
            field=models.IntegerField(help_text='Cost to purchase items', null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Food_Vendor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Food_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Pizza_desc',
            field=models.CharField(max_length=100, null=True, verbose_name='Type of Pizza'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Ps_reference',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Special', 'Special'), ('Beef', 'Beef')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_store',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Others', 'Others'), ('Fuel', 'Fuel'), ('Ice Cream', 'Ice Cream'), ('Fruits', 'Fruits'), ('Bread', 'Bread'), ('Shawarma', 'Shawarma'), ('Pizza', 'Pizza'), ('Drugs', 'Drugs'), ('Food', 'Food')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='description',
            field=models.CharField(blank=True, help_text='Further description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='fruits_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='fruits_purchase_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Location'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='fuel_per_amount',
            field=models.IntegerField(help_text='25Ltrs max per order (N163/ltr, N4075-25ltrs', null=True, verbose_name='Petrol Amount'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='ice_Cream_desc',
            field=models.CharField(max_length=100, null=True, verbose_name='Ice Cream Description'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='ice_Cream_store',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='order_id',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='payment_channel',
            field=models.CharField(choices=[('Card/Transfer', 'Card/Transfer')], max_length=100, null=True, verbose_name='Payment Choice'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='pizza_store',
            field=models.CharField(max_length=100, null=True, verbose_name='Place of Purchase'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On Route for Delivery', 'On route for Delivery'), ('Purchase in Process', 'Purchase in Process'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='Amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter an estimated amount, our charges Inclusive', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='Amount_Refunded',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='Charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='Item_Cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='order_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('At the Mall', 'At the Mall'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
    ]
