# Generated by Django 3.1.7 on 2021-07-07 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_auto_20210706_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='Ps_reference',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Bread_brand_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Bread Name'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Drug_store',
            field=models.CharField(help_text="Write 'None' if None", max_length=100, null=True, verbose_name='Pharmacy Name'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Special', 'Special'), ('Beef', 'Beef')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_store',
            field=models.CharField(help_text='write None if None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Others', 'Others'), ('Pizza', 'Pizza'), ('Food', 'Food'), ('Bread', 'Bread'), ('Shawarma', 'Shawarma'), ('Drugs', 'Drugs'), ('Ice Cream', 'Ice Cream'), ('Fruits', 'Fruits'), ('Fuel', 'Fuel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Purchase in Process', 'Purchase in Process'), ('Delivered', 'Delivered'), ('On Route for Delivery', 'On route for Delivery')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='Address_of_reciever',
            field=models.CharField(max_length=100, null=True, verbose_name='Reciever Address'),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='Package_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='reciever_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Reciever Name'),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='reciever_phone_number',
            field=models.CharField(help_text='This Format:070xxxxxxxx', max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Number'),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='Address_of_reciever',
            field=models.CharField(max_length=100, null=True, verbose_name='Reciever Address'),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='Package_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='reciever_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='reciever_phone_number',
            field=models.CharField(help_text='This Format:070xxxxxxxx', max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Reciever Number'),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='Address',
            field=models.CharField(max_length=200, null=True, verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='Amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter an estimated amount, our charges Inclusive.', max_digits=10),
        ),
    ]
