# Generated by Django 3.1.7 on 2021-07-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_auto_20210707_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Special', 'Special')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Drugs', 'Drugs'), ('Ice Cream', 'Ice Cream'), ('Fruits', 'Fruits'), ('Pizza', 'Pizza'), ('Shawarma', 'Shawarma'), ('Food', 'Food'), ('Bread', 'Bread'), ('Fuel', 'Fuel'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Purchase in Process', 'Purchase in Process'), ('On Route for Delivery', 'On route for Delivery'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('At the Mall', 'At the Mall'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
