# Generated by Django 3.1.7 on 2021-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0116_auto_20210728_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_desk',
            name='Delivery_Fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='front_desk',
            name='Total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Special', 'Special')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Drugs', 'Drugs'), ('Food', 'Food'), ('Gas', 'Gas'), ('Others', 'Others'), ('Bread', 'Bread'), ('Ice Cream', 'Ice Cream'), ('Fruits', 'Fruits'), ('Pizza', 'Pizza'), ('Fuel', 'Fuel'), ('Shawarma', 'Shawarma')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On Route for Delivery', 'On route for Delivery'), ('Pending', 'Pending'), ('Purchase in Process', 'Purchase in Process')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
