# Generated by Django 3.1.7 on 2021-08-06 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeControl', '0007_auto_20210726_1203'),
        ('users', '0121_auto_20210805_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymous',
            name='riders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BikeControl.ridersprofile'),
        ),
        migrations.AddField(
            model_name='errand_service',
            name='riders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BikeControl.ridersprofile'),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='riders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BikeControl.ridersprofile'),
        ),
        migrations.AddField(
            model_name='makerequestcash',
            name='riders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BikeControl.ridersprofile'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='riders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BikeControl.ridersprofile'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Beef', 'Beef'), ('Chicken', 'Chicken'), ('Special', 'Special')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Pizza', 'Pizza'), ('Bread', 'Bread'), ('Fuel', 'Fuel'), ('Drugs', 'Drugs'), ('Food', 'Food'), ('Others', 'Others'), ('Ice Cream', 'Ice Cream'), ('Fruits', 'Fruits'), ('Shawarma', 'Shawarma')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On Route for Delivery', 'On route for Delivery'), ('Purchase in Process', 'Purchase in Process')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='customer_payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Transfer & Cash', 'Transfer & Cash'), ('Transfer', 'Transfer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('At the Mall', 'At the Mall'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
    ]
