# Generated by Django 3.1.7 on 2021-08-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0125_auto_20210810_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='customer_payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer & Cash', 'Transfer & Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Special', 'Special'), ('Chicken', 'Chicken'), ('Beef', 'Beef')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Ice Cream', 'Ice Cream'), ('Gas', 'Gas'), ('Bread', 'Bread'), ('Drugs', 'Drugs'), ('Food', 'Food'), ('Fruits', 'Fruits'), ('Shawarma', 'Shawarma'), ('Fuel', 'Fuel'), ('Others', 'Others'), ('Pizza', 'Pizza')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Purchase in Process', 'Purchase in Process'), ('On Route for Delivery', 'On route for Delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='customer_payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer & Cash', 'Transfer & Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('At the Mall', 'At the Mall'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
