# Generated by Django 3.1.7 on 2021-09-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0133_auto_20210901_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='customer_payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Transfer & Cash', 'Transfer & Cash'), ('Transfer', 'Transfer'), ('Cash', 'Cash')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Department',
            field=models.CharField(choices=[(None, None), ('FIRST LOGISTICS', 'FIRST LOGISTICS'), ('FIRST MARINE', 'FIRST MARINE'), ('IWH', 'IWH')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Designation',
            field=models.CharField(choices=[(None, None), ('MARKETING', 'MARKETING'), ('ICT', 'ICT'), ('FLEET MANAGER', 'FLEET MANAGER'), ('FRONT DESK', 'FRONT DESK'), ('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('ACCOUNT', 'ACCOUNT'), ('DEPOT MANAGER', 'DEPOT MANAGER'), ('OPERATIONS', 'OPERATIONS'), ('ADMIN MANAGER', 'ADMIN MANAGER')], default='ACCOUNT', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Special', 'Special'), ('Beef', 'Beef')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Shawarma', 'Shawarma'), ('Gas', 'Gas'), ('Others', 'Others'), ('Pizza', 'Pizza'), ('Food', 'Food'), ('Fuel', 'Fuel'), ('Drugs', 'Drugs'), ('Ice Cream', 'Ice Cream'), ('Fruits', 'Fruits'), ('Bread', 'Bread')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='Amount_Paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='customer_payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Transfer & Cash', 'Transfer & Cash'), ('Transfer', 'Transfer'), ('Cash', 'Cash')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='profit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('At the Mall', 'At the Mall'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
    ]
