# Generated by Django 3.1.7 on 2021-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0135_auto_20210915_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='customer_payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer & Cash', 'Transfer & Cash'), ('Transfer', 'Transfer'), ('Card', 'Card')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Designation',
            field=models.CharField(choices=[(None, None), ('MARKETING', 'MARKETING'), ('ICT', 'ICT'), ('FLEET MANAGER', 'FLEET MANAGER'), ('FRONT DESK', 'FRONT DESK'), ('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('ACCOUNT', 'ACCOUNT'), ('DEPOT MANAGER', 'DEPOT MANAGER'), ('OPERATIONS', 'OPERATIONS'), ('ADMIN MANAGER', 'ADMIN MANAGER'), ('COMMERCIAL', 'COMMERCIAL')], default='ACCOUNT', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Ice Cream', 'Ice Cream'), ('Gas', 'Gas'), ('Food', 'Food'), ('Drugs', 'Drugs'), ('Pizza', 'Pizza'), ('Others', 'Others'), ('Shawarma', 'Shawarma'), ('Bread', 'Bread'), ('Fuel', 'Fuel'), ('Fruits', 'Fruits')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Purchase in Process', 'Purchase in Process'), ('Pending', 'Pending'), ('On Route for Delivery', 'On route for Delivery')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='customer_payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer & Cash', 'Transfer & Cash'), ('Transfer', 'Transfer'), ('Card', 'Card')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall')], default='Pending', max_length=20, null=True),
        ),
    ]
