# Generated by Django 3.1.7 on 2021-09-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0137_auto_20210922_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='customer_payment_method',
            field=models.CharField(choices=[('Transfer & Cash', 'Transfer & Cash'), ('Cash', 'Cash'), ('Transfer', 'Transfer'), ('Card', 'Card')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Designation',
            field=models.CharField(choices=[(None, None), ('MARKETING', 'MARKETING'), ('ICT', 'ICT'), ('FLEET MANAGER', 'FLEET MANAGER'), ('FRONT DESK', 'FRONT DESK'), ('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('ACCOUNT', 'ACCOUNT'), ('DEPOT MANAGER', 'DEPOT MANAGER'), ('OPERATIONS', 'OPERATIONS'), ('ADMIN MANAGER', 'ADMIN MANAGER'), ('COMMERCIAL', 'COMMERCIAL'), ('MANAGER_PH', 'MANAGER_PH')], default='ACCOUNT', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Special', 'Special'), ('Beef', 'Beef'), ('Chicken', 'Chicken')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Fuel', 'Fuel'), ('Others', 'Others'), ('Pizza', 'Pizza'), ('Bread', 'Bread'), ('Ice Cream', 'Ice Cream'), ('Shawarma', 'Shawarma'), ('Fruits', 'Fruits'), ('Drugs', 'Drugs'), ('Food', 'Food'), ('Gas', 'Gas')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Route for Delivery', 'On route for Delivery'), ('Purchase in Process', 'Purchase in Process'), ('Delivered', 'Delivered')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='customer_payment_method',
            field=models.CharField(choices=[('Transfer & Cash', 'Transfer & Cash'), ('Cash', 'Cash'), ('Transfer', 'Transfer'), ('Card', 'Card')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
    ]
