# Generated by Django 3.1.7 on 2021-11-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0145_auto_20211031_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='customer_payment_method',
            field=models.CharField(choices=[('Transfer & Cash', 'Transfer & Cash'), ('Transfer', 'Transfer'), ('Card', 'Card'), ('Cash', 'Cash')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Special', 'Special'), ('Chicken', 'Chicken'), ('Beef', 'Beef')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Ice Cream', 'Ice Cream'), ('Pizza', 'Pizza'), ('Shawarma', 'Shawarma'), ('Fruits', 'Fruits'), ('Bread', 'Bread'), ('Fuel', 'Fuel'), ('Food', 'Food'), ('Others', 'Others'), ('Drugs', 'Drugs'), ('Gas', 'Gas')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Purchase in Process', 'Purchase in Process'), ('On Route for Delivery', 'On route for Delivery'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='customer_payment_method',
            field=models.CharField(choices=[('Transfer & Cash', 'Transfer & Cash'), ('Transfer', 'Transfer'), ('Card', 'Card'), ('Cash', 'Cash')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('At the Mall', 'At the Mall'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
    ]
