# Generated by Django 3.1.7 on 2021-11-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0148_auto_20211101_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='customer_payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Transfer', 'Transfer'), ('Transfer & Cash', 'Transfer & Cash')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Special', 'Special')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Bread', 'Bread'), ('Drugs', 'Drugs'), ('Gas', 'Gas'), ('Pizza', 'Pizza'), ('Fruits', 'Fruits'), ('Others', 'Others'), ('Ice Cream', 'Ice Cream'), ('Fuel', 'Fuel'), ('Shawarma', 'Shawarma'), ('Food', 'Food')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('On Route for Delivery', 'On route for Delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Purchase in Process', 'Purchase in Process')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='customer_payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Transfer', 'Transfer'), ('Transfer & Cash', 'Transfer & Cash')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
