# Generated by Django 3.1.7 on 2021-12-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0154_auto_20211210_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='customer_payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer'), ('Transfer & Cash', 'Transfer & Cash')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='Shawarma_desc',
            field=models.CharField(choices=[('Special', 'Special'), ('Beef', 'Beef'), ('Chicken', 'Chicken')], max_length=100, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Shawarma', 'Shawarma'), ('Drugs', 'Drugs'), ('Others', 'Others'), ('Gas', 'Gas'), ('Fuel', 'Fuel'), ('Bread', 'Bread'), ('Food', 'Food'), ('Ice Cream', 'Ice Cream'), ('Pizza', 'Pizza')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errand_service',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On Route for Delivery', 'On route for Delivery'), ('Purchase in Process', 'Purchase in Process'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='customer_payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer'), ('Transfer & Cash', 'Transfer & Cash')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='front_desk',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerequestcash',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('At the Mall', 'At the Mall'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
