# Generated by Django 3.1.7 on 2021-08-23 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0131_auto_20210823_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='OFFICE_REPORT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_schedule', models.TextField(max_length=500, null=True)),
                ('Work_description', models.CharField(max_length=100, null=True)),
                ('extent_of_completion', models.CharField(max_length=100, null=True)),
                ('time_taken', models.CharField(max_length=100, null=True)),
                ('work_left', models.CharField(max_length=100, null=True)),
                ('challenges', models.TextField(max_length=500, null=True)),
                ('feedback_chairman', models.CharField(max_length=100, null=True)),
                ('feedback_operations', models.CharField(max_length=100, null=True)),
                ('feedback_admin', models.CharField(max_length=100, null=True)),
                ('solutions', models.CharField(max_length=100, null=True)),
                ('operations_seen', models.BooleanField(default=False)),
                ('chairman_seen', models.BooleanField(default=False)),
                ('admin_seen', models.BooleanField(default=False)),
                ('attended_to', models.BooleanField(default=False)),
                ('ticket_num', models.CharField(max_length=5, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
