# Generated by Django 3.1.7 on 2021-08-23 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management_Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_message', models.CharField(max_length=100, null=True)),
                ('notification_ID', models.CharField(max_length=5, null=True)),
                ('viewed', models.BooleanField(default=False, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='office_report',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='extent_of_completion',
            field=models.CharField(choices=[(None, None), ('Just Started', 'Just Started'), ('Far From Completion', 'Far From Completion'), ('Almost Completed', 'Almost Completed'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='time_taken',
            field=models.CharField(choices=[(None, None), ('0-1HR', '0-1HR'), ('1-2HRS', '1-2HRS'), ('2-3HRS', '2-3HRS'), ('3-4HRS', '3-4HRS'), ('4-5HRS', '4-5HRS')], max_length=100, null=True),
        ),
    ]
