# Generated by Django 3.1.7 on 2021-08-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20210823_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office_report',
            name='Status',
        ),
        migrations.AddField(
            model_name='office_report',
            name='Categoty',
            field=models.CharField(choices=[('Operations', 'Operations'), ('Fleet', 'Fleet'), ('ICT', 'ICT'), ('Front', 'Front'), ('Market', 'Market')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Fleet_challenges',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Fleet_report',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Fleet_report_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Fleet_solutions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='FrontDesk_challenges',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='FrontDesk_report',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='FrontDesk_report_Title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='FrontDesk_solutions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Front_desk_total_amount',
            field=models.IntegerField(null=True, verbose_name='Total Amount Today'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Front_desk_total_rides',
            field=models.IntegerField(null=True, verbose_name='Total Rides Today'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Ict_challenges',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Ict_report',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Ict_report_Title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Ict_solutions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Marketing_report',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Marketing_report_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Marketing_solutions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Marketting_challenges',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
