# Generated by Django 3.1.7 on 2021-09-01 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0133_auto_20210901_1016'),
        ('Management', '0005_auto_20210829_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='Iwh_challenges',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Challenges'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Iwh_report',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Iwh_report_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Iwh_solutions',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Solutions'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Tank_farm_challenges',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Challenges'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Tank_farm_report',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Tank_farm_report_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Report Title'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Tank_farm_solutions',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Solutions'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='for_chairman_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer', verbose_name='STAFF'),
        ),
    ]
