# Generated by Django 3.1.7 on 2021-09-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20210901_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office_report',
            old_name='submit',
            new_name='for_admin_operation_runyi',
        ),
        migrations.AddField(
            model_name='office_report',
            name='Runyi_challenges',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Runyi_report',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Runyi_report_Title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Runyi_solutions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='feedback_Manager_FLM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='for_mangerFLLS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office_report',
            name='manager_flm_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Categoty',
            field=models.CharField(choices=[('Operations', 'Operations'), ('Fleet', 'Fleet'), ('ICT', 'ICT'), ('Front', 'Front'), ('Market', 'Market'), ('Tank Farm', 'Tank Farm'), ('IWH', 'IWH')], max_length=100, null=True),
        ),
    ]
