# Generated by Django 3.1.7 on 2021-09-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20210901_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='Manager_challenges',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Manager_report',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Manager_report_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Manager_solutions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Categoty',
            field=models.CharField(choices=[('Operations', 'Operations'), ('Fleet', 'Fleet'), ('ICT', 'ICT'), ('Front', 'Front'), ('Market', 'Market'), ('Tank Farm', 'Tank Farm'), ('IWH', 'IWH'), ('RUNYI', 'RUNYI')], max_length=100, null=True),
        ),
    ]
