# Generated by Django 3.1.7 on 2021-09-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20210901_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_report',
            name='Categoty',
            field=models.CharField(choices=[('Operations', 'Operations'), ('Fleet', 'Fleet'), ('ICT', 'ICT'), ('Front', 'Front'), ('Market', 'Market'), ('Tank Farm', 'Tank Farm'), ('IWH', 'IWH'), ('RUNYI', 'RUNYI'), ('MANAGER', 'MANAGER')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Iwh_solutions',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Solutions'),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Tank_farm_solutions',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Solutions'),
        ),
    ]
