# Generated by Django 3.1.7 on 2021-09-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0011_auto_20210909_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_report',
            name='Work_description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Main Report'),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='challenges',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='extent_of_completion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Task Completed'),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='solutions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='time_taken',
            field=models.TextField(choices=[(None, None), ('0-1HR', '0-1HR'), ('1-2HRS', '1-2HRS'), ('2-3HRS', '2-3HRS'), ('3-4HRS', '3-4HRS'), ('4-5HRS', '4-5HRS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='work_left',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Task Left'),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='work_schedule',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Task Schedule'),
        ),
    ]
