# Generated by Django 3.1.7 on 2021-09-15 14:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_auto_20210915_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_report',
            name='Fleet_challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Fleet_report',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='FrontDesk_challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='FrontDesk_report',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Ict_challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Ict_report',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Iwh_challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Challenges'),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Iwh_report',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Manager_challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Manager_report',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Marketing_report',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Marketting_challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Runyi_challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Runyi_report',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Tank_farm_challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Challenges'),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Tank_farm_report',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Work_description',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Main Report'),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='extent_of_completion',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Task Completed'),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='time_taken',
            field=tinymce.models.HTMLField(choices=[(None, None), ('0-1HR', '0-1HR'), ('1-2HRS', '1-2HRS'), ('2-3HRS', '2-3HRS'), ('3-4HRS', '3-4HRS'), ('4-5HRS', '4-5HRS')], max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='work_left',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, null=True, verbose_name='Task Left'),
        ),
    ]
