# Generated by Django 3.1.7 on 2021-09-20 10:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_auto_20210915_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='Commectial_Report_Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Commercial_Accomplishment',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Acomplishment'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Commercial_Balance',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Commercial_Breakdown',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Break Down'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Commercial_Challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Challenges'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Commercial_Report',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Report Details'),
        ),
    ]
