# Generated by Django 3.1.7 on 2021-09-23 08:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0018_auto_20210922_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='Account_challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Account_report_details',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Account_report_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Account_solutions',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Admin_challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Admin_report_details',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Admin_report_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Admin_solutions',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Fleet_solutions',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='FrontDesk_solutions',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Ict_solutions',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Iwh_solutions',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Manager_solutions',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Marketing_solutions',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Runyi_solutions',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='solutions',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
    ]
