# Generated by Django 3.1.7 on 2021-09-23 09:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0019_auto_20210923_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='Maintenacne_report_details',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Maintenance_challenges',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Maintenance_report_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Maintenance_solutions',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Commercial_Balance',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Company GOV | Total truck out | Stock balance'),
        ),
    ]
