# Generated by Django 3.1.7 on 2021-09-23 11:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0020_auto_20210923_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='Manager_challenges_PH',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Challenges'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Manager_report_PH',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Report Details'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Manager_report_title_PH',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Report Title'),
        ),
        migrations.AddField(
            model_name='office_report',
            name='Manager_solutions_PH',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Solutions'),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Categoty',
            field=models.CharField(choices=[('Operations', 'Operations'), ('Fleet', 'Fleet'), ('ICT', 'ICT'), ('Front', 'Front'), ('Market', 'Market'), ('Tank Farm', 'Tank Farm'), ('IWH', 'IWH'), ('RUNYI', 'RUNYI'), ('MANAGER', 'MANAGER'), ('COMMERCIAL', 'COMMERCIAL'), ('ADMIN', 'ADMIN'), ('ACCOUNT', 'ACCOUNT'), ('MAINTENANCE', 'MAINTENANCE')], max_length=100, null=True),
        ),
    ]
