# Generated by Django 3.1.7 on 2021-09-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0021_auto_20210923_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='seen_admin_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office_report',
            name='seen_manager_flls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office_report',
            name='seen_operations_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office_report',
            name='seen_runyi_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office_report',
            name='seenn_GGM_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='Categoty',
            field=models.CharField(choices=[('Operations', 'Operations'), ('Fleet', 'Fleet'), ('ICT', 'ICT'), ('Front', 'Front'), ('Market', 'Market'), ('Tank Farm', 'Tank Farm'), ('IWH', 'IWH'), ('RUNYI', 'RUNYI'), ('MANAGER', 'MANAGER'), ('COMMERCIAL', 'COMMERCIAL'), ('ADMIN', 'ADMIN'), ('ACCOUNT', 'ACCOUNT'), ('MAINTENANCE', 'MAINTENANCE'), ('MANAGER_PH', 'MANAGER_PH')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='for_manager_FLM',
            field=models.BooleanField(default=False, verbose_name='For GGM'),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='for_operation',
            field=models.BooleanField(default=False, verbose_name='For Manager Operation'),
        ),
    ]
