# Generated by Django 3.1.7 on 2021-09-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0022_auto_20210925_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='TimeSeenOperations_feedback',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
