# Generated by Django 3.1.7 on 2021-09-25 22:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0023_office_report_timeseenoperations_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='TimeSeenAdmin_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='TimeSeenChairman_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='TimeSeenGGM_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='TimeSeenManagerFlls_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='TimeSeenRunyi_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='seenn_Chairman_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='TimeSeenOperations_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='office_report',
            name='time_taken',
            field=tinymce.models.HTMLField(blank=True, choices=[(None, None), ('0-1HR', '0-1HR'), ('1-2HRS', '1-2HRS'), ('2-3HRS', '2-3HRS'), ('3-4HRS', '3-4HRS'), ('4-5HRS', '4-5HRS')], max_length=2000, null=True),
        ),
    ]
