# Generated by Django 3.1.7 on 2021-09-26 16:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0024_auto_20210925_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_report',
            name='feedback_manager',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, null=True),
        ),
    ]
