# Generated by Django 3.1.7 on 2021-09-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0025_auto_20210926_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='admin_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office_report',
            name='chairman_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office_report',
            name='fllsManager_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office_report',
            name='managerAdmin_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office_report',
            name='operation_given',
            field=models.BooleanField(default=False),
        ),
    ]
