# Generated by Django 3.1.7 on 2021-09-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0026_auto_20210928_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='GGM_given',
            field=models.BooleanField(default=False),
        ),
    ]
