# Generated by Django 3.1.7 on 2021-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0027_office_report_ggm_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_report',
            name='timeAdmin_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='timeChairman_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='timeGGM_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='timeGMadmin_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='timeManagerFlls_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='office_report',
            name='timeOperation_feedback',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
