# Generated by Django 3.1.7 on 2021-10-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0028_auto_20210930_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_report',
            name='Commectial_Report_Title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Commercial Report'),
        ),
    ]
